version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.8.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "18:1c:84:41:3d:e6:16:ba:6e:00:c7:aa:f9:2d:38:60"
      - checkout
      - run:
          name: Verify on master branch
          command: test "$CIRCLE_BRANCH" == "master"
      - setup_remote_docker
      - restore_cache:
          key: deps-v3-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install python dependencies
          command: pipenv install
      - save_cache:
          key: deps-v2-{{ checksum "Pipfile.lock" }}
          paths:
           - "~/.local/share/virtualenvs/"
      - run:
          name: Get versions, build, tag and push to docker hub
          command: |
            FORCE=$(if git log --pretty=format:"%s" HEAD^..HEAD | grep -q '\[force\]'; then echo "--force"; else echo ""; fi)
            pipenv run python build_versions.py $FORCE
          no_output_timeout: 30m
      - run:
          name: Add new versions to git (if any)
          command: ./git_archive.sh

workflows:
   version: 2
   build_on_commit:
     jobs:
       - build:
           filters:
              branches:
                only:
                  - master
